version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"  # מיפוי פורט 80 בקונטיינר לפורט 3000 במחשב המארח
    environment:
      - REACT_APP_API_URL=http://server:5000  # הגדרת הכתובת של השרת
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"  # מיפוי פורט 5000 בקונטיינר לפורט 5000 במחשב המארח
