version: '3.9'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"  
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000  
  server:
    build:
      context: ./server
    ports:
      - "5000:3000"
    environment:
      - PORT= 3000